### ISSUE TITLE
Cannot initialize ZanoWallet

### ISSUE THREAD

**Issue by jkatayama** [hyle-team/zano_native_lib_package_ios#1]
### Description:
Regardless of what parameters are set, the `init` method throws an internal error.

### Steps to Reproduce the Issue:
1. Open this SDK with Xcode.  
2. Call the `testInitAddress()` method (You can just run `ZanoWalletTests.testExample` and check the console log).

### Expected Behavior:
The initialization method should not return an error.

### Actual Behavior:
```json
{
  "error": {
    "code": "INTERNAL_ERROR",
    "message": "[init] @ /Users/roky/projects/Zano/mobile_repo/mobile/zano_native_lib/zano/src/wallet/plain_wallet_api.cpp:237 \nmessage:Read-only file system"
  },
  "id": 0,
  "jsonrpc": "",
  "method": ""
}
```

### Environment:

- Xcode: 15.4
- Version of ZanoWallet: 2.0.0.336 [132d2bf]

###  Logs, screenshots, or any other relevant information
logs on XCode
[log.txt](https://github.com/user-attachments/files/17045151/log.txt)

**Comment by cryptozoidberg** [comment]
The path that passed to init as working dir should be available for writing, here is a possible code for iOS/Android: 

for android it use this code (java):
```
String myString = getReactApplicationContext().getFilesDir().getAbsolutePath();
```
for ios it use this code (objectiveC)
```
NSFileManager *fileManager = [NSFileManager defaultManager];
NSURL *docsDir = [fileManager URLForDirectory:NSDocumentDirectory inDomain:NSUserDomainMask appropriateForURL:nil create:YES error:nil];
NSString *strX = [docsDir path];
```
